config/routes.rb
Rails.application.routes.draw do

  root "blogs#index"

  resources :blogs, only:[:index] do
    collection do
      post 'upload_img'
      get 'set'
      post 'set_userinfo'
      get 'set_blog'
      post 'update_blog'
      get 'about'
      get 'change_password'
      post 'update_password'
      post 'preview'
    end

  end

  resources :articles do
    member do
      post 'star'
    end

    resources :comments
  end

  get 'register' => 'users#register'
  get 'login' => 'users#login'
  get 'logout' => 'users#logout'
  resources :users do
    collection do
      get 'register'
      post 'register_confirm'
      get 'login'
      post 'login_confirm'
      get 'logout'
    end
  end

end

app/models/user.rb
#encoding: utf-8
class User < ActiveRecord::Base
  has_secure_password

  has_many :articles
  has_many :comments, class_name: 'ArticleComment'

  before_save :set_admin
  validates :username, length: {minimum: 5, maximum: 20}, uniqueness: true
  validates :email, format: {with: /\A[a-zA-Z0-9\-]+@[a-zA-Z0-9-]+\.(org|com|cn|io|net|cc|me)\z/}, uniqueness: true
  validates :password, length: {minimum: 6}, confirmation: true, if: :need_valid_password?
  validates :nick_name, length: {minimum: 2, maximum: 20}, uniqueness: true, if: 'nick_name.present?'

  def nickname
    self.nick_name || self.username
  end

  def set_admin
    self.admin = 0 unless self.admin.present?
  end

  def check_password(password)
    self.authenticate(password)
  end

  def update_last_reply_time
    self.update_attribute last_reply_time: DateTime.now
  end

  def can_reply?
    (DateTime.now.to_i - self.last_reply_time.to_i) > 60
  end

  def need_valid_password?
    new_record? || password.present?
  end
end

app/controllers/users_controller.rb
#encoding: utf-8
class UsersController < ApplicationController
  def register
    @user = User.new
    render 'register', layout: 'register'
  end

  def register_confirm
    @user = User.new params.require(:user).permit(:username,:email,:password,:password_confirmation)
    if @user.save
      to_login @user
      redirect_to root_path
    else
      render 'register', layout: 'register'
    end
  end

  def login
    return redirect_to(login_path(from: referer)) unless params[:from].present?
    @user = User.new
    render 'login', layout: 'register'
  end

  def login_confirm
    @user = User.find_by username: params[:user][:username]
    if @user && @user.check_password(params[:user][:password])
      to_login @user
      @user.update_attribute :last_login_time, DateTime.now
      redirect_to (params[:from].present? ? params[:from] : root_path)
    else
      flash[:error] = '用户名或密码错误'
      render 'login', layout: 'register'
    end
  rescue
    flash[:error] = '用户名或密码错误'
    render 'login', layout: 'register'
  end

  def logout
    session[:user_id] = nil
    redirect_to referer
  end

  protected

  def to_login(user)
    session[:user_id] = user.id
  end
end

app/views/users/_form.html.haml
- method = action == 'update' ? 'put' : 'post'
- submit_url = case action; when 'register'; register_confirm_users_path; when 'login'; login_confirm_users_path; when 'update'; user_path(@user); end
= form_for @user, method: method, url: submit_url, role: 'form' do |f|
  .form-field.form-group
    = f.text_field :username, placeholder: '用户名', class: 'form-control username', required: true
  .form-field.form-group
    = f.text_field :email, placeholder: '邮箱', class: 'form-control email', required: true
  .form-field.form-group
    = f.password_field :password, placeholder: '密码，最少6位', class: 'form-control password', required: true
  .form-field.form-group
    = f.password_field :password_confirmation, placeholder: '确认密码', class: 'form-control password', required: true
  = submit_tag '注册', class: 'btn btn-primary btn-lg'
  .action-wrapper
    = link_to '已有账号？', login_path

app/views/users/login.html.haml
%section.content
  .form-unit
    = link_to root_path, class: 'brand' do
      %h1 Blog
    %h3 用户登录
    - errors = @user ? @user.errors.full_messages : []
    - if errors.any?
      .alert.alert-danger
        %a.close{"data-dismiss"=>"alert"} &times;
        %span
          = errors.first
    - if flash[:success].present?
      .alert.alert-success
        %a.close{"data-dismiss"=>"success"} &times;
        %span
          = flash[:success]
    - elsif flash[:error].present?
      .alert.alert-danger
        %a.close{"data-dismiss"=>"alert"} &times;
        %span= flash[:error]
    = form_for :user, url: login_confirm_users_path, role: 'form' do |f|
      .form-field.form-group
        = f.text_field :username, placeholder: '用户名', class: 'form-control username', required: true
      .form-field.form-group
        = f.password_field :password, placeholder: '密码', class: 'form-control password', required: true
      = submit_tag '登录', class: 'btn btn-primary btn-lg'
      .action-wrapper
        = link_to '没有账号？', register_path

app/views/users/register.html.haml
%section.content
  .form-unit
    = link_to root_path, class: 'brand' do
      %h1 Blog
    %h3 注册账号
    - errors = @user.errors.full_messages
    - if errors.any?
      .alert.alert-danger
        %a.close{"data-dismiss"=>"alert"} &times;
        %span
          = errors.first
    = render partial: 'form', locals: {action: 'register'}